app/__init__.py
from flask import Flask
from flask_socketio import SocketIO
from flask_bcrypt import Bcrypt
from flask_login import LoginManager
from flask_sqlalchemy import SQLAlchemy
from setup import DATABASE_URL

socketio = SocketIO()
bcrypt = Bcrypt()
login_manager = LoginManager()
login_manager.session_protection = 'strong'
login_manager.login_view = 'main.main_page'

db = SQLAlchemy()


def create_app(debug=True):

    app = Flask(__name__)
    app.config['SECRET_KEY'] = 'secret KEY SHHH!'
    app.config['SQLALCHEMY_DATABASE_URI'] = DATABASE_URL
    app.config['SQLALCHEMY_COMMIT_ON_TEARDOWN'] = True

    app.debug = debug

    login_manager.init_app(app)
    socketio.init_app(app)
    bcrypt.init_app(app)
    db.init_app(app)

    from .main import main as main_blueprint

    app.register_blueprint(main_blueprint)

    return app

app/main/__init__.py
from flask import Blueprint

main = Blueprint('main', __name__)

from . import views, events, errors

app/main/views.py
from app import db
from datetime import datetime
from flask import render_template, redirect, url_for, flash, session, request, jsonify
from flask_login import login_user, login_required, logout_user

from . import main
from .form import LoginForm, RegisterForm, NewRoomForm, SaveRoomForm

from ..database import UserModel, RoomModel
from ..utils import pick_color, id_generator, gen_short_id, get_long_id


@main.route('/', methods=['GET', 'POST'])
def main_page():
    form = LoginForm()
    if form.validate_on_submit():
        user = UserModel.query.filter_by(username=form.username.data).first()
        if user and user.verify_password(form.password.data):
            login_user(user)
            session['username'] = form.username.data

            flash('logged in', 'green accent-3')
            return redirect(url_for('main.dashboard'))
    return render_template('main.html',
                           form=form)


@main.route('/logout', methods=['GET'])
@login_required
def logout():
    logout_user()
    flash('You have been logged out.', 'green accent-3')
    return redirect(url_for('main.main_page'))


@main.route('/register', methods=['GET', 'POST'])
def register():
    form = RegisterForm()
    if form.validate_on_submit():
        try:
            user = UserModel(username=form.username.data,
                             password=form.password.data,
                             color=pick_color())
            db.session.add(user)
            db.session.commit()
            flash('You are registered', 'green accent-3')
            return redirect(url_for('main.main_page'))
        except Exception as e:
            print(str(e))
            flash('Not registered, Something went wrong', 'red')
            return redirect(url_for('main.main_page'))
    return render_template('register.html',
                           form=form)


@main.route('/chat/<r_id>')
@login_required
def chat(r_id):
    room_id = r_id
    session['room'] = room_id
    user = session['username']
    user_query = UserModel.query.filter_by(username=user).first()
    session['color'] = user_query.get_color()
    room_obj = RoomModel.query.filter_by(short_id=room_id).first()
    room_name = room_obj.name
    return render_template('chat.html',
                           user=user,
                           room_id=room_id,
                           room_name=room_name)


@main.route('/chat/delete/<r_id>')
@login_required
def delete_room(r_id):
    try:
        room = RoomModel.query.filter_by(short_id=r_id).first()
        db.session.delete(room)
        db.session.commit()
    except Exception as e:
        print(str(e))
        db.session.rollback()
        flash('Something went wrong', 'red')
    return redirect(url_for('main.dashboard'))


@main.route('/dashboard', methods=['GET', 'POST'])
@login_required
def dashboard():
    user_name = session['username']
    new_room_form = NewRoomForm()
    save_room_form = SaveRoomForm()

    user = UserModel.query.filter_by(username=user_name).first()
    rooms = RoomModel.query.filter_by(admin_id=user.id).all()

    room_list = []
    for obj in rooms:
        dict_list = {'id': obj.short_id, 'name': obj.name}
        room_list.append(dict_list)

    saved_room_list = []
    user_saved_list = user.rooms.all()

    for room in user_saved_list:
        temp_dict = {'id': room.short_id, 'name': room.name}
        saved_room_list.append(temp_dict)

    return render_template('dashboard.html',
                           user=user_name,
                           new_room_form=new_room_form,
                           save_room_form=save_room_form,
                           saved_room_list=saved_room_list,
                           room_list=room_list)


@main.route('/newRoom', methods=['POST'])
def newroom():

    user = session['username']
    room_name = request.form['room_name']

    if user and room_name:

        room_admin = UserModel.query.filter_by(username=user).first()
        room_id = id_generator()
        new_room = RoomModel(short_id=gen_short_id(room_id),
                             name=room_name,
                             admin=room_admin,
                             created=datetime.utcnow())
        try:
            db.session.add(new_room)
            db.session.commit()

            template = render_template('_micro.html',
                                       id=gen_short_id(room_id),
                                       name=room_name)

            return jsonify({'response': template})

        except:

            return jsonify({'error': 'Something went wrong'})


@main.route('/saveRoom', methods=['POST'])
def saveroom():

    user = session['username']
    room_short_id = request.form['room_id']

    if user and room_short_id:

        room_user = UserModel.query.filter_by(username=user).first()
        if 'http' in room_short_id:
            link_split = room_short_id.split('/')
            r_short_id = link_split[-1]
            room = RoomModel.query.filter_by(short_id=r_short_id).first()
        else:

            room = RoomModel.query.filter_by(short_id=room_short_id).first()

        try:
            room_user.rooms.append(room)
            db.session.add(room_user)
            db.session.commit()

            template = render_template('_micro.html',
                                       id=room.short_id,
                                       name=room.name)

            return jsonify({'response': template})

        except:
            db.session.rollback()
            return jsonify({'error': 'Something went wrong'})

app/templates/_micro.html
<tr>
<td>{{name}}</td>
<td><a href="chat/{{id}}" class="btn">Enter Room</a></td>
<td><button class="btn blue-grey darken-3" id="copy-button" data-clipboard-text="http://localhost:5000/chat/{{id}}">
Copy to clipboard </button> </td>
<td><a href="chat/delete/{{id}}" class="btn red darken-4">Delete Room</a></td>
</tr>

app/templates/base.html
<html>
      <head>
      {% block head %}
        <!--Import Google Icon Font-->
        <link href="http://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
        <!--Import materialize.css-->
        <script type="text/javascript" src="https://code.jquery.com/jquery-2.1.1.min.js"></script>

        <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.8/css/materialize.min.css">
        <!--Let browser know website is optimized for mobile-->
        <link type="text/css" rel="stylesheet" href="{{ url_for('static', filename='style.css')}}">

        <meta name="viewport" content="width=device-width, initial-scale=1.0"/>

        <title>{% block title %}{% endblock %} Oblivion </title>
      {% endblock %}


      </head>

    <body class="grey lighten-4">
    {% block body %}

        <nav>
          <div class="nav-wrapper  red darken-1">
            <a href="#!" class="brand-logo center">Oblivion</a>
            <a href="#" data-activates="mobile-demo" class="button-collapse"><i class="material-icons">menu</i></a>
            <ul class="right hide-on-med-and-down">

              {% if current_user.is_authenticated %}
                <li><a id='dashboard' class="white-text red darken-4" href="{{url_for('main.dashboard')}}">Dashboard</a></li>
              {% endif %}

              {% if current_user.is_authenticated %}
               <li><a id="logout" class="white-text red darken-4" href="{{url_for('main.logout')}}">Logout</a></li>
               {% else %}
               <li><a class="white-text red darken-4" href="{{url_for('main.register')}}">Register</a></li>
              {% endif %}

              <li><a href="#"></a></li>
              <li><a href="#"></a></li>
              <li><a href="#"></a></li>
            </ul>
            <ul class="side-nav" id="mobile-demo">


              {% if current_user.is_authenticated %}
                <li><a class="white-text red accent-3" href="{{url_for('main.dashboard')}}">Dashboard</a></li>
              {% endif %}
              {% if not current_user.is_authenticated %}
                <li><a class="white-text red accent-3" href="{{url_for('main.register')}}">Register</a></li>
              {% endif %}
              {% if current_user.is_authenticated %}
                <li><a id="logout_2" class="white-text red accent-3" href="{{url_for('main.logout')}}">Logout</a></li>
               {% endif %}

                <li><a href="#"></a></li>
              <li><a href="#"></a></li>
            </ul>
          </div>
        </nav>

        {% block content %}

        <div class="container">
            <div class="row">
              {% with messages = get_flashed_messages(with_categories=true) %}
                {% if messages %}
                  {% for category, message in messages %}
                    <div class="row">
                      <div class="col s12">
                        <div class="chip {{category}}">
                          {{message}}
                          <i class="close material-icons">close</i>
                        </div>
                      </div>
                    </div>
                  {% endfor %}
                {% endif %}
              {% endwith %}
            </div>
            <div class="row">
              {% block page_content %} {% endblock %}
            </div>
        </div>
    {% endblock %}

        <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.97.7/js/materialize.min.js"></script>
        <script src="https://cdn.jsdelivr.net/clipboard.js/1.5.13/clipboard.min.js"></script>
        <script type="text/javascript" src="{{url_for('static', filename='js/base.js')}}"></script>


      {% endblock %}
    </body>

</html>

app/templates/chat.html
{% extends 'base.html' %}

{% block head %}
    <style>
        .message_title {
              font-size: 16px;
              font-style: Black;
              font-weight: bold;
              text-decoration: underline;
              }
        .current_user {
             color: transparent;
        }
    </style>
    {{ super() }}
    <script src="https://cdn.socket.io/socket.io-1.4.5.js"></script>
    <script type="text/javascript" src="{{url_for('static', filename='js/chatroom.js')}}"></script>

{% endblock %}

{% block page_content %}


      <div class="row">
        <div class="col s9">
          <div class="card">
            <div class="card-content " >
            <span class="card-title"><b>Room:  {{room_name}}</b></span>
              <ul class="collection " id="messages"><span id="stuff" class="badge red white-text"></span>

              </ul>
            </div>
              <div class="card-content" id="card"><span id="type_span" class="badge blue white-text"></span>
                <span>Me: @</span><span id="current_user">{{user}}</span>

                 <input placeholder="Send chat" type="text" id="mymessage">

              </div>

            <div class="card-action">
                <button class="btn" id="sendbutton">Send</button>
                <a href="{{url_for('main.dashboard')}}" class="btn red darken-4" id="closebutton">Leave room</a>
                <td><button class="btn blue-grey darken-3" id="copy-button" data-clipboard-text="http://localhost:5000/chat/{{room_id}}">Copy Room Id  </button> </td>

            </div>
          </div>
        </div>

        <div class="col s3">
            <div class="card-panel">
              <table class="bordered">
                <thead>
                  <tr>
                      <th data-field="id">Users Online</th>
                  </tr>
                </thead>
                <tbody id="user_online">
                </tbody>
              </table>
            </div>
        </div>

      </div>

{% endblock %}

app/templates/dashboard.html
{% extends 'base.html' %}

{% block page_content %}

      <div class="row">
        <div class="col s12">
          <div class="card ">
            <div class="card-content black-text">
              <span id ="user_title_name" class="card-title"> Username: <b>{{user}}</b></span>
            </div>

               <div class="row">
                <div class="col s12">
                  <ul class="tabs">
                    <li class="tab col s6"><a href="#create">Create Room</a></li>
                    <li class="tab col s6"><a href="#save">Save Room</a></li>
                  </ul>
                </div>

                <div id="create" class="col s6">
                    <div class="container">
                       <div class="col s12">
                        <form id="newRoomForm" action={{url_for('main.newroom')}} method="POST">
                            {{ new_room_form.csrf_token }}

                            <div class="row">
                                <div class="input-field black-text">
                                    {{new_room_form.room_name}}

                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field black-text">
                                    {{new_room_form.submit(class="btn red darken-4")}}
                                </div>
                            </div>
                        </form>
                      </div>
                    </div>

                </div>
                <div id="save" class="col s6">
                    <div class="container">
                       <div class="col s12">
                        <form id="saveRoomForm" action={{url_for('main.saveroom')}} method="POST">
                            {{ save_room_form.csrf_token }}

                            <div class="row">
                                <div class="input-field black-text">
                                    {{save_room_form.room_id}}
                                </div>
                            </div>

                            <div class="row">
                                <div class="input-field black-text">
                                    {{save_room_form.submit(class="btn blue-grey darken-3")}}
                                </div>
                            </div>
                        </form>
                       </div>

                    </div>
                </div>

                </div>
          </div>
        </div>
      </div>


      <div class="row">
        <div class="col s12">
          <div class="card ">
            <div class="card-content black-text">
              <span class="card-title">My Rooms</span>
            </div>
            <div>
                <table>
                <thead>
                  <tr>
                      <th data-field="id">Room Name</th>
                      <th data-field="name"></th>
                      <th data-field="name"></th>

                  </tr>
                </thead>
                 <tbody id="roomTable">
                 {% for user in room_list %}
                  <tr>
                    <td>{{user['name'] }}</td>
                    <td><a href="chat/{{user['id']}}" class="btn">Enter Room</a></td>
                    <td><button class="btn blue-grey darken-3" id="copy-button" data-clipboard-text="http://localhost:5000/chat/{{user['id']}}">
                    Copy to clipboard</button> </td>
                    <td><a href="chat/delete/{{user['id']}}" class="btn red darken-4">Delete Room</a></td>
                  </tr>
                 {% endfor %}
                 </tbody>
                </table>
            </div>
          </div>
        </div>
      </div>

      <div class="row">
        <div class="col s12">
          <div class="card ">
            <div class="card-content black-text">
              <span class="card-title">Saved Rooms</span>
            </div>
            <div>
                <table>
                <thead>
                  <tr>
                      <th data-field="id">Room Name</th>
                      <th data-field="name"></th>
                      <th data-field="name"></th>
                  </tr>
                </thead>
                 <tbody id="saverRoomTable">
                 {% for user in saved_room_list %}
                  <tr>
                    <td>{{user['name'] }}</td>
                    <td><a href="chat/{{user['id']}}" class="btn">Enter Room</a></td>
                    <td><button class="btn blue-grey darken-3" id="copy-button" data-clipboard-text="http://localhost:5000/chat/{{user['id']}}">
                    Copy to clipboard</button> </td>
                    <td><a href="chat/delete/{{user['id']}}" class="btn red darken-4">Delete Room</a></td>
                  </tr>
                 {% endfor %}
                 </tbody>
                </table>
            </div>
          </div>
        </div>
      </div>


    <script type="text/javascript" src="{{url_for('static', filename='js/dashboard.js')}}"></script>

{% endblock %}

app/templates/main.html
{% extends 'base.html' %}

{% block page_content %}

<div class="container">

    <div class="row">
        <div class="col s9 offset-s1">

            <div class="card">
                <div class="card-content black-text">
                <span class="card-title">Login</span>
                    <div class="row">

                    <form class="col s12" action="{{url_for('main.main_page')}}" method="POST">
                        {{ form.csrf_token }}

                        <div class="row">
                            <div class="input-field col s12 black-text">
                                {{form.username}}{{form.username.label(class="black-text")}}
                            </div>
                        </div>

                        <div class="row">
                            <div class="input-field col s12">
                                {{form.password}}{{form.password.label(class="black-text")}}
                            </div>
                        </div>

                        <div class="row">
                            {{form.login(class="btn-large red darken-4")}}
                        </div>
                    </form>

                    </div>
                </div>
            </div>

            <div class="row">
                 <div class="col s12" >
                </div>
            </div>

        </div>
    </div>
    <br><br>
</div>


{% endblock %}

app/templates/register.html
{% extends 'base.html' %}

{% block page_content %}

<div class="container">

    <div class="row">
        <div class="col s9 offset-s1">

            <div class="card">
                <div class="card-content black-text">
                <span class="card-title">Login</span>
                    <div class="row">

                        <form class="col s12" action={{url_for('main.register')}} method="POST">
                            {{ form.csrf_token }}

                            <div class="row">
                                <div class="input-field col s12 black-text">
                                    {{form.username}}{{form.username.label(class="black-text")}}
                                </div>
                                {% if form.username.errors %}
                                <div>
                                {% for error in form.username.errors %}
                                   <span class="chip red accent-2">{{ error }}<i class="close material-icons">close</i>
                                   </span>

                                {% endfor %}
                                </div>
                                {% endif %}
                            </div>

                            <div class="row">
                                <div class="input-field col s12">
                                    {{form.password}}{{form.password.label(class="black-text")}}
                                </div>

                            </div>

                             <div class="row">
                                <div class="input-field col s12">
                                    {{form.password_2}}{{form.password_2.label(class="black-text")}}
                                </div>
                            </div>

                            <div class="row">
                                {{form.submit(class="btn-large red darken-4")}}
                            </div>
                        </form>

                    </div>
                </div>
            </div>
        </div>
    </div>
    <br><br>
</div>


{% endblock %}